CREATE TABLE email_verification_token
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token   VARCHAR(255)                            NOT NULL,
    user_id BIGINT                                  NOT NULL,
    used    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_emailverificationtoken PRIMARY KEY (id)
);

ALTER TABLE users
    ADD email_verified BOOLEAN;

ALTER TABLE users
    ALTER COLUMN email_verified SET NOT NULL;

ALTER TABLE email_verification_token
    ADD CONSTRAINT uc_emailverificationtoken_token UNIQUE (token);

ALTER TABLE email_verification_token
    ADD CONSTRAINT uc_emailverificationtoken_user UNIQUE (user_id);

ALTER TABLE email_verification_token
    ADD CONSTRAINT FK_EMAILVERIFICATIONTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
