CREATE TABLE otp_verification
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    otp         VARCHAR(255),
    valid_until TIMESTAMP WITHOUT TIME ZONE,
    used        BOOLEAN                                 NOT NULL,
    user_id     BIGINT,
    CONSTRAINT pk_otp_verification PRIMARY KEY (id)
);

ALTER TABLE otp_verification
    ADD CONSTRAINT FK_OTP_VERIFICATION_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
