CREATE TABLE session
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token            VARCHAR(255),
    user_id          BIGINT,
    expiration_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_session PRIMARY KEY (id)
);

ALTER TABLE session
    ADD CONSTRAINT FK_SESSION_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
